name:                tic-tac-toe
version:             0.1.0.0
github:              "githubuser/tic-tac-toe"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A simple 2-player tic-tac-toe console game application in Haskell. Chief purpose is to demonstrate project structure and unit testing in Haskell.

dependencies:
- base   >= 4.7 && < 5
- vector
- mtl
- hspec
- QuickCheck
- directory
- hspec-expectations
- random
- transformers
  
library:
  source-dirs: src

executables:
  tic-tac-toe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - tic-tac-toe

tests:
  tic-tac-toe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - tic-tac-toe
